CREATE TABLE UZYTKOWNIK(
UZYTKOWNIK_ID NUMBER(11) NOT NULL,
PLEC VARCHAR2(20),
KOD_POCZTOWY VARCHAR2(8) NOT NULL,
MIASTO VARCHAR2(255) NOT NULL,
WOJEWODZTWO VARCHAR2(255) NOT NULL,
CONSTRAINT UZYTKOWNIK_PK PRIMARY KEY(UZYTKOWNIK_ID) ENABLE
);

CREATE TABLE ZAMOWIENIE(
ZAMOWIENIE_ID NUMBER(11) NOT NULL,
UZYTKOWNIK_ID NUMBER(11) NOT NULL,
DATA_ZAM DATE NOT NULL,
KWOTA NUMBER(10) NOT NULL,
TYP_PLATNOSCI varchar(255) NOT NULL,
CONSTRAINT ZAMOWIENIE_PK PRIMARY KEY(ZAMOWIENIE_ID) ENABLE,
CONSTRAINT ZAMOWIENIE__UZYTKOWNIK_FK
    FOREIGN KEY (UZYTKOWNIK_ID)
    REFERENCES UZYTKOWNIK(UZYTKOWNIK_ID) ENABLE
);

CREATE TABLE PRODUKT(
PRODUKT_ID NUMBER(11) NOT NULL,
ZAMOWIENIE_ID NUMBER(11) NOT NULL,
NAZWA VARCHAR(255),
CENA NUMBER(10), -- cena historyczna z dnia zakupu
KATEGORIA VARCHAR2(255) NOT NULL,
CONSTRAINT PRODUKT__ZAMOWIENIE_FK
    FOREIGN KEY (ZAMOWIENIE_ID)
    REFERENCES ZAMOWIENIE(ZAMOWIENIE_ID) ENABLE
);

CREATE INDEX PRODUKT_ZAMOWIENIE_INDEX ON PRODUKT (PRODUKT_ID, ZAMOWIENIE_ID);