CREATE TABLE UZYTKOWNIK(
UZYTKOWNIK_ID NUMBER(10) NOT NULL,
IMIE VARCHAR2(50) NOT NULL,
NAZWISKO VARCHAR2(100) NOT NULL,
EMAIL VARCHAR2(100) NOT NULL,
TELEFON NUMBER(11),
PLEC VARCHAR2(20),
TYP NUMBER(2) NOT NULL,
CONSTRAINT UZYTKOWNIK_PK PRIMARY KEY(UZYTKOWNIK_ID) ENABLE
);

CREATE TABLE ADRES(
ADRES_ID NUMBER(10) NOT NULL,
ULICA VARCHAR2(255) NOT NULL,
NR_DOMU NUMBER(6) NOT NULL,
NR_MIESZKANIA NUMBER(6),
KOD_POCZTOWY NUMBER(5) NOT NULL,
MIASTO VARCHAR2(255) NOT NULL,
WOJEWODZTWO VARCHAR2(255) NOT NULL,
CONSTRAINT ADRES_PK PRIMARY KEY(ADRES_ID) ENABLE
);

CREATE TABLE ZAMOWIENIE(
ZAMOWIENIE_ID NUMBER(10) NOT NULL,
DATA_ZAM DATE NOT NULL,
CONSTRAINT ZAMOWIENIE_PK PRIMARY KEY(ZAMOWIENIE_ID) ENABLE
);

CREATE TABLE PLATNOSC(
PLATNOSC_ID NUMBER(10) NOT NULL,
TYP NUMBER(3) NOT NULL,
KWOTA NUMBER(10) NOT NULL,
STATUS NUMBER(3) NOT NULL,
CONSTRAINT PLATNOSC_PK PRIMARY KEY(PLATNOSC_ID) ENABLE
);

CREATE TABLE KATEGORIA(
KATEGORIA_ID NUMBER(10) NOT NULL,
NAZWA VARCHAR2(255) NOT NULL,
CONSTRAINT KATEGORIA_PK PRIMARY KEY(KATEGORIA_ID) ENABLE
);

CREATE TABLE PRODUKT(
PRODUKT_ID NUMBER(10) NOT NULL,
NAZWA VARCHAR(255) NOT NULL,
CENA NUMBER(10) NOT NULL,
OPIS VARCHAR(2048) NOT NULL,
STAN NUMBER(10) NOT NULL,
KATEGORIA_ID NUMBER(10) NOT NULL,
CONSTRAINT PRODUKT_PK PRIMARY KEY(PRODUKT_ID) ENABLE,
CONSTRAINT PRODUKT__KATEGORIA_FK
	FOREIGN KEY (KATEGORIA_ID)
	REFERENCES KATEGORIA(KATEGORIA_ID) ENABLE
);

CREATE TABLE ZAMOWIENIE_PRODUKT(
ZAMOWIENIE_ID NUMBER(10) NOT NULL,
PRODUKT_ID NUMBER(10) NOT NULL,
ILOSC NUMBER(10) NOT NULL,
CENA NUMBER(10) NOT NULL,
CONSTRAINT ZAMOWIENIE_PRODUKT__ZAMOWIENIE_FK
    FOREIGN KEY (ZAMOWIENIE_ID)
    REFERENCES ZAMOWIENIE(ZAMOWIENIE_ID) ENABLE,
CONSTRAINT ZAMOWIENIE_PRODUKT__PRODUKT_FK
	FOREIGN KEY (PRODUKT_ID)
	REFERENCES PRODUKT(PRODUKT_ID) ENABLE
);

CREATE TABLE ZAMOWIENIE_PLATNOSC(
ZAMOWIENIE_ID NUMBER(10) NOT NULL,
PLATNOSC_ID NUMBER(10) NOT NULL,
CONSTRAINT ZAMOWIENIE_PLATNOSC__ZAMOWIENIE_FK
    FOREIGN KEY (ZAMOWIENIE_ID)
    REFERENCES ZAMOWIENIE(ZAMOWIENIE_ID) ENABLE,
CONSTRAINT ZAMOWIENIE_PLATNOSC__PLATNOSC_FK
	FOREIGN KEY (PLATNOSC_ID)
	REFERENCES PLATNOSC(PLATNOSC_ID) ENABLE,
CONSTRAINT ZAMOWIENIE_PLATNOSC__ZAMOWIENIE_ID_UNIQUE UNIQUE (ZAMOWIENIE_ID) ENABLE,
CONSTRAINT ZAMOWIENIE_PLATNOSC__PLATNOSC_ID_UNIQUE UNIQUE (PLATNOSC_ID) ENABLE
);

CREATE TABLE UZYTKOWNIK_ADRES(
UZYTKOWNIK_ID NUMBER(10) NOT NULL,
ADRES_ID NUMBER(10) NOT NULL,
CONSTRAINT UZYTKOWNIK_ADRES__UZYTKOWNIK_FK
    FOREIGN KEY (UZYTKOWNIK_ID)
    REFERENCES UZYTKOWNIK(UZYTKOWNIK_ID) ENABLE,
CONSTRAINT UZYTKOWNIK_ADRES__ADRES_FK
    FOREIGN KEY (ADRES_ID)
    REFERENCES ADRES(ADRES_ID) ENABLE,
CONSTRAINT UZYTKOWNIK_ADRES__UZYTKOWNIK_ID_UNIQUE UNIQUE (UZYTKOWNIK_ID) ENABLE
);

CREATE TABLE UZYTKOWNIK_ZAMOWIENIE(
UZYTKOWNIK_ID NUMBER(10) NOT NULL,
ZAMOWIENIE_ID NUMBER(10) NOT NULL,
CONSTRAINT UZYTKOWNIK_ZAMOWIENIE__UZYTKOWNIK_FK
    FOREIGN KEY (UZYTKOWNIK_ID)
    REFERENCES UZYTKOWNIK(UZYTKOWNIK_ID) ENABLE,
CONSTRAINT UZYTKOWNIK_ZAMOWIENIE__ZAMOWIENIE_FK
    FOREIGN KEY (ZAMOWIENIE_ID)
    REFERENCES ZAMOWIENIE(ZAMOWIENIE_ID) ENABLE,
CONSTRAINT UZYTKOWNIK_ZAMOWIENIE__ZAMOWIENIE_ID_UNIQUE UNIQUE (ZAMOWIENIE_ID) ENABLE
);